version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_container
    restart: always
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: image_upload
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: